FROM python:3.8-alpine

WORKDIR /usr/local/app
COPY ./app/requirements.txt ./

RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install gunicorn

EXPOSE 80

CMD gunicorn application.startup:api \
        --bind=0.0.0.0:80 \
        --reload \
        --access-logfile - \
        --log-level debug
